### ISSUE TITLE
Possible license issue

### ISSUE THREAD

**Issue by S-S-X** [MCLV-pandorabox/mt_ShipOS#1]
Reading commit comment for 6f78e609ac8104827437c959265652713bcfd5eb it seems like you wanted to allow anyone to utilize this code for just about any purpose.
What you really did by removing license was prohibiting every possible use case for example redistributing, copying or editing this code is now illegal almost everywhere in the world because of copyright laws.

Most often it really doesn't matter in practice but to protect users (other people) and to make it clear that you want to share it you should add license.

So if you want to share then you should also add license, if I understood your comment correctly and you want to allow anyone to do almost anything with your code you could take a look at MIT-0, CC0 or Unlicense licenses.

**Comment by MCLV-pandorabox** [comment]
Thanks. I think I'll do that, although I first decided against it because I have to all add those lines of text and I've to put my name on it. But I realized later that I could just use the Github handle.

**Comment by MCLV-pandorabox** [comment]
Licence is now MIT-0
